import time
import pandas as pd
from google import genai
from google.genai import errors

from config import GOOGLE_API_KEY, MODEL_NAME


# =========================================================
# GEMINI CLIENT & RETRY ENGINE
# =========================================================

def get_client():
    if not GOOGLE_API_KEY:
        raise ValueError(
            "GOOGLE_API_KEY is not configured. "
            "Please add GOOGLE_API_KEY in Streamlit Cloud Secrets "
            "or your local .env file."
        )
    return genai.Client(api_key=GOOGLE_API_KEY)


def call_gemini_with_retry(prompt: str, max_retries: int = 3, initial_delay: float = 3.0) -> str:
    """
    Executes a Gemini API call with exponential backoff retry on 429 Rate Limit errors.
    """
    delay = initial_delay

    for attempt in range(max_retries):
        try:
            client = get_client()
            response = client.models.generate_content(
                model=MODEL_NAME,
                contents=prompt
            )

            if hasattr(response, "text") and response.text:
                return response.text

            return "⚠️ No response text was generated by Gemini."

        except errors.APIError as e:
            # Check for 429 status code or Resource Exhausted messages
            is_429 = getattr(e, 'code', None) == 429 or "429" in str(e) or "RESOURCE_EXHAUSTED" in str(e)

            if is_429 and attempt < max_retries - 1:
                time.sleep(delay)
                delay *= 2  # Double delay for next attempt (3s -> 6s -> 12s)
                continue
            elif is_429:
                return (
                    "### ⏳ Quota Limit Reached (429)\n\n"
                    "The Gemini API rate limit or daily free tier quota has been exceeded.\n\n"
                    "**Quick Solutions:**\n"
                    "1. **Wait 10–15 seconds** and try again.\n"
                    "2. Change `MODEL_NAME` in `config.py` to `gemini-2.5-flash` or `gemini-2.0-flash`.\n"
                    "3. Add a billing account to your Google AI Studio project for higher quota limits."
                )
            else:
                return f"### ❌ Gemini API Error\n\n```\n{str(e)}\n```"

        except Exception as e:
            return f"### ❌ Unexpected Error\n\n```\n{str(e)}\n```"


# =========================================================
# GENERATE CHART INSIGHTS
# =========================================================

def generate_chart_insights(df: pd.DataFrame, chart_type: str, x_column: str, y_column: str = None) -> str:
    """
    Generate AI insights for a visualization.
    """
    sample = df.head(20).to_string(index=False)

    prompt = f"""
You are an Expert Data Scientist and Business Intelligence Analyst.

Analyze the following dataset sample and visualization.

{sample}

Chart Type : {chart_type}
X Axis : {x_column}
Y Axis : {y_column}

Provide the report in Markdown format with the following headings:
## 📌 Executive Summary
## 📊 Key Statistics
## 📈 Important Trends
## 🚨 Outliers
## 💼 Business Insights
## ⚠ Risks
## 💡 Recommendations
## 🧹 Data Cleaning Suggestions
## 🔮 Future Analysis
## ⭐ Overall Conclusion

Keep the explanation simple, professional, and detailed.
"""

    return call_gemini_with_retry(prompt)


# =========================================================
# GENERATE DATASET SUMMARY
# =========================================================

def generate_dataset_summary(df: pd.DataFrame) -> str:
    """
    Generate AI summary for uploaded dataset.
    """
    sample = df.head(30).to_string(index=False)

    prompt = f"""
You are an expert Data Scientist.

Below is a dataset sample:

{sample}

Generate a professional report with:
## Dataset Overview
## Data Quality
## Missing Values
## Duplicate Records
## Outlier Analysis
## Interesting Patterns
## Business Insights
## Recommended Charts
## Machine Learning Opportunities
## Final Summary

Return Markdown only.
"""

    return call_gemini_with_retry(prompt)


# =========================================================
# ASK DATASET QUESTION
# =========================================================

def ask_dataset_question(df: pd.DataFrame, question: str) -> str:
    """
    Ask questions about the uploaded dataset.
    """
    sample = df.head(30).to_string(index=False)

    prompt = f"""
You are an expert Data Scientist.

Below is a sample of the user's dataset:

{sample}

User Question: {question}

Answer the user's question clearly using the dataset.
If the answer cannot be determined from the sample, state that more data may be required.
"""

    return call_gemini_with_retry(prompt)


# =========================================================
# GENERATE CLEANING SUGGESTIONS
# =========================================================

def generate_cleaning_suggestions(df: pd.DataFrame) -> str:
    """
    Generate AI-powered cleaning recommendations.
    """
    sample = df.head(30).to_string(index=False)

    prompt = f"""
You are a Senior Data Cleaning Expert.

Analyze the dataset sample below:

{sample}

Provide professional recommendations including:
## Missing Values
## Duplicate Rows
## Invalid Data
## Datatype Problems
## Outliers
## Feature Engineering
## Encoding Suggestions
## Scaling Suggestions
## Final Cleaning Strategy

Return Markdown only.
"""

    return call_gemini_with_retry(prompt)


# =========================================================
# DATA QUALITY SCORE
# =========================================================

def generate_data_quality_score(df: pd.DataFrame) -> int:
    """
    Calculate a simple data quality score.
    """
    try:
        rows = len(df)
        cols = len(df.columns)
        missing = int(df.isnull().sum().sum())
        duplicates = int(df.duplicated().sum())

        total_cells = rows * cols
        if total_cells == 0:
            return 0

        missing_ratio = missing / total_cells
        duplicate_ratio = duplicates / max(rows, 1)

        score = 100
        score -= missing_ratio * 60
        score -= duplicate_ratio * 40

        return max(0, min(100, round(score)))

    except Exception:
        return 0


# =========================================================
# QUALITY BADGE
# =========================================================

def get_quality_badge(score: int) -> str:
    if score >= 90:
        return "🟢 Excellent"
    elif score >= 75:
        return "🟡 Good"
    elif score >= 50:
        return "🟠 Fair"
    return "🔴 Poor"
