"""
==========================================================
AI CLEANER MODULE
DataForge AI
==========================================================
"""

from google import genai
from config import GOOGLE_API_KEY, MODEL_NAME



client = genai.Client(api_key=GOOGLE_API_KEY)


def generate_chart_insights(df, chart_type, x_column, y_column=None):
    """
    Generate AI insights for a visualization.
    """

    try:

        sample = df.head(20).to_string(index=False)

        prompt = f"""
You are an Expert Data Scientist and Business Intelligence Analyst.

Analyze the following dataset sample and visualization.

====================================================
DATASET SAMPLE
====================================================

{sample}

====================================================
VISUALIZATION DETAILS
====================================================

Chart Type : {chart_type}

X Axis : {x_column}

Y Axis : {y_column}

====================================================
GENERATE A PROFESSIONAL REPORT
====================================================

Provide the report in Markdown.

## 📌 Executive Summary

## 📊 Key Statistics

## 📈 Important Trends

## 🚨 Outliers

## 💼 Business Insights

## ⚠ Risks

## 💡 Recommendations

## 🧹 Data Cleaning Suggestions

## 🔮 Future Analysis

## ⭐ Overall Conclusion

Keep the explanation simple, professional and detailed.
"""

        response = client.models.generate_content(
            model=MODEL_NAME,
            contents=prompt
        )

        if hasattr(response, "text") and response.text:
            return response.text

        return "No response generated by Gemini."

    except Exception as e:

        return f"""
# ❌ AI Analysis Failed

**Error**

{str(e)}

Please verify:

- Google API Key
- MODEL_NAME
- Internet Connection
- Gemini API Quota
"""




def generate_dataset_summary(df):
    """
    Generate AI summary for uploaded dataset.
    """

    try:

        sample = df.head(30).to_string(index=False)

        prompt = f"""
You are an expert Data Scientist.

Below is a dataset sample.

{sample}

Generate a professional report with:

## Dataset Overview

## Data Quality

## Missing Values

## Duplicate Records

## Outlier Analysis

## Interesting Patterns

## Business Insights

## Recommended Charts

## Machine Learning Opportunities

## Final Summary

Return Markdown only.
"""

        response = client.models.generate_content(
            model=MODEL_NAME,
            contents=prompt
        )

        if hasattr(response, "text") and response.text:
            return response.text

        return "No response generated."

    except Exception as e:

        return f"Dataset Summary Error: {e}"


def ask_dataset_question(df, question):
    """
    Ask questions about the uploaded dataset.
    """

    try:

        sample = df.head(30).to_string(index=False)

        prompt = f"""
You are an expert Data Scientist.

Below is a sample of the user's dataset.

====================================================
DATASET
====================================================

{sample}

====================================================
QUESTION
====================================================

{question}

Answer the user's question clearly using the dataset.
If the answer cannot be determined from the sample,
state that more data may be required.
"""

        response = client.models.generate_content(
            model=MODEL_NAME,
            contents=prompt
        )

        if hasattr(response, "text") and response.text:
            return response.text

        return "No response generated."

    except Exception as e:
        return f"AI Chat Error:\n\n{e}"




def generate_cleaning_suggestions(df):
    """
    Generate AI-powered cleaning recommendations.
    """

    try:

        sample = df.head(30).to_string(index=False)

        prompt = f"""
You are a Senior Data Cleaning Expert.

Analyze the dataset sample below.

====================================================
DATASET
====================================================

{sample}

Provide professional recommendations.

Include:

## Missing Values

## Duplicate Rows

## Invalid Data

## Datatype Problems

## Outliers

## Feature Engineering

## Encoding Suggestions

## Scaling Suggestions

## Final Cleaning Strategy

Return Markdown.
"""

        response = client.models.generate_content(
            model=MODEL_NAME,
            contents=prompt
        )

        if hasattr(response, "text") and response.text:
            return response.text

        return "No response generated."

    except Exception as e:
        return f"Cleaning Suggestion Error:\n\n{e}"



def generate_data_quality_score(df):
    """
    Calculate a simple data quality score.
    """

    try:

        rows = len(df)
        cols = len(df.columns)

        missing = int(df.isnull().sum().sum())
        duplicates = int(df.duplicated().sum())

        total_cells = rows * cols

        if total_cells == 0:
            return 0

        missing_ratio = missing / total_cells
        duplicate_ratio = duplicates / max(rows, 1)

        score = 100

        score -= missing_ratio * 60
        score -= duplicate_ratio * 40

        score = max(0, min(100, round(score)))

        return score

    except Exception:
        return 0




def get_quality_badge(score):

    if score >= 90:
        return "🟢 Excellent"

    elif score >= 75:
        return "🟡 Good"

    elif score >= 50:
        return "🟠 Fair"

    return "🔴 Poor"